package com.example.mmo.MMO.World.Tiles;

import android.graphics.RectF;

import com.example.mmo.R;

public class TileAtributes {

    public TileAtributes(Tile[] first, Tile[] second){
        /*first[4].setBounds(new RectF(8, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[5].setBounds(new RectF(0, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[6].setBounds(new RectF(0, 8, Tile.TILEWIDTH - 8, Tile.TILEWIDTH), true);
        first[36].setBounds(new RectF(8, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[38].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 8, Tile.TILEWIDTH), true);
        first[68].setBounds(new RectF(8, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 8), true);
        first[69].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 8), true);
        first[70].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 8, Tile.TILEWIDTH - 8), true);*/

        first[1].setSolid(false);
        first[2].setSolid(false);
        first[3].setSolid(false);
        first[4].setBounds(new RectF(8, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[5].setBounds(new RectF(0, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[6].setBounds(new RectF(0, 8, Tile.TILEWIDTH - 8, Tile.TILEWIDTH), true);
        first[8].setBounds(new RectF(0, Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH), false);
        first[9].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[11].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[12].setSolid(false);
        first[15].setSolid(false);
        first[17].setSolid(false);
        first[18].setSolid(false);
        first[19].setSolid(false);
        first[21].setSolid(false);
        first[23].setSolid(false);
        first[24].setSolid(false);
        first[25].setSolid(false);
        first[27].setSolid(false);
        first[30].setSolid(false);
        first[33].setSolid(false);
        first[34].setSolid(false);
        first[35].setSolid(false);
        first[36].setBounds(new RectF(8, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[38].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 8, Tile.TILEWIDTH), true);
        first[43].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[44].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[45].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[49].setSolid(false);
        first[50].setSolid(false);
        first[51].setSolid(false);
        first[52].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[53].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[54].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[55].setSolid(false);
        first[56].setSolid(false);
        first[57].setSolid(false);
        first[65].setSolid(false);
        first[66].setSolid(false);
        first[67].setSolid(false);
        first[68].setBounds(new RectF(8, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 8), true);
        first[69].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 8), true);
        first[70].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 8, Tile.TILEWIDTH - 8), true);
        first[72].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[73].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[81].setSolid(false);
        first[82].setSolid(false);
        first[83].setSolid(false);
        first[84].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[86].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[87].setSolid(false);
        first[88].setSolid(false);
        first[89].setSolid(false);
        first[97].setSolid(false);
        first[98].setSolid(false);
        first[99].setSolid(false);
        first[103].setSolid(false);
        first[104].setSolid(false);
        first[105].setSolid(false);
        first[113].setSolid(false);
        first[114].setSolid(false);
        first[115].setSolid(false);
        first[116].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[117].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[118].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), false);
        first[119].setSolid(false);
        first[120].setSolid(false);
        first[121].setSolid(false);
        first[135].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[136].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[137].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[138].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[139].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[140].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[141].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[142].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[143].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[144].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[145].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[146].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[161].setSolid(false);
        first[163].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[164].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[165].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[166].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[167].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[170].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[171].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[172].setBounds(new RectF(Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 3 * 2, Tile.TILEWIDTH / 3 * 2), false);
        first[173].setSolid(false);
        first[175].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[176].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[177].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[178].setBounds(new RectF(0, Tile.TILEWIDTH / 3, Tile.TILEWIDTH / 2, Tile.TILEWIDTH), false);
        first[179].setBounds(new RectF(Tile.TILEWIDTH / 2, Tile.TILEWIDTH / 3, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[181].setSolid(false);
        first[182].setSolid(false);
        first[183].setSolid(false);
        first[184].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[185].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[186].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[192].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[193].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[194].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[195].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[197].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[204].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[205].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[206].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[207].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[209].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[213].setSolid(false);
        first[214].setSolid(false);
        first[215].setSolid(false);
        first[216].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[218].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), true);
        first[224].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[226].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[227].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[228].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[229].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), true);
        first[230].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[231].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[232].setSolid(false);
        first[234].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[235].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[236].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[238].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[239].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[240].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[241].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), true);
        first[242].setBounds(new RectF(Tile.TILEWIDTH / 2, 0, Tile.TILEWIDTH, 80), false);
        first[243].setBounds(new RectF(0, 0, Tile.TILEWIDTH / 2, 80), false);
        first[245].setSolid(false);
        first[246].setSolid(false);
        first[247].setSolid(false);
        first[248].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[249].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), true);
        first[250].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), true);
        first[251].setBounds(new RectF(12, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[252].setBounds(new RectF(0, 12, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[253].setBounds(new RectF(0, 12, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[256].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[257].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[258].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), false);
        first[262].setSolid(false);
        first[263].setSolid(false);
        first[264].setSolid(false);
        first[265].setSolid(false);
        first[266].setSolid(false);
        first[267].setSolid(false);
        first[268].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[269].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[270].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), false);
        first[274].setSolid(false);
        first[275].setSolid(false);
        first[276].setSolid(false);
        first[277].setSolid(false);
        first[278].setSolid(false);
        first[279].setSolid(false);
        first[283].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH), false);
        first[285].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH), false);
        first[294].setBounds(new RectF(8, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[295].setBounds(new RectF(0, 8, Tile.TILEWIDTH, Tile.TILEWIDTH), true);
        first[296].setBounds(new RectF(0, 8, Tile.TILEWIDTH - 8, Tile.TILEWIDTH), true);
        first[315].setBounds(new RectF(12, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[316].setBounds(new RectF(0, 0, Tile.TILEWIDTH, Tile.TILEWIDTH - 12), false);
        first[317].setBounds(new RectF(0, 0, Tile.TILEWIDTH - 12, Tile.TILEWIDTH - 12), false);

    }
}
